brew "git"
brew "micro"
brew "newsboat"
brew "node"
brew "tmux"
brew "fastfetch"
brew "eza"
brew "starship"
brew "zoxide"

cask "wezterm"
cask "font-victor-mono-nerd-font"
cask "font-symbols-only-nerd-font"
